# Generated by Django 3.1.3 on 2021-01-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onlinegrocery', '0002_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_date',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fruits', 'fruits'), ('Vegitables', 'vegitables'), ('Meat', 'meat'), ('Chicken', 'chicken')], max_length=50, null=True),
        ),
    ]
